// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/y-miyazaki/absc/internal/aws/resources/core"
	"go.uber.org/mock/gomock"
)

// MockRunCollector is a mock of RunCollector interface.
type MockRunCollector struct {
	ctrl     *gomock.Controller
	recorder *MockRunCollectorMockRecorder
	isgomock struct{}
}

// MockRunCollectorMockRecorder is the mock recorder for MockRunCollector.
type MockRunCollectorMockRecorder struct {
	mock *MockRunCollector
}

// NewMockRunCollector creates a new mock instance.
func NewMockRunCollector(ctrl *gomock.Controller) *MockRunCollector {
	mock := &MockRunCollector{ctrl: ctrl}
	mock.recorder = &MockRunCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunCollector) EXPECT() *MockRunCollectorMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockRunCollector) Collect(context1 context.Context, schedule *core.Schedule, s string, s1 string, targetHints core.TargetHints, collectOptions core.CollectOptions) ([]core.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", context1, schedule, s, s1, targetHints, collectOptions)
	runs, _ := ret[0].([]core.Run)
	err, _ := ret[1].(error)
	return runs, err
}

// Collect indicates an expected call of Collect.
func (mr *MockRunCollectorMockRecorder) Collect(context1, schedule, s, s1, targetHints, collectOptions any) *MockRunCollectorCollectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockRunCollector)(nil).Collect), context1, schedule, s, s1, targetHints, collectOptions)
	return &MockRunCollectorCollectCall{Call: call}
}

// MockRunCollectorCollectCall wrap *gomock.Call
type MockRunCollectorCollectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunCollectorCollectCall) Return(runs []core.Run, err error) *MockRunCollectorCollectCall {
	c.Call = c.Call.Return(runs, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunCollectorCollectCall) Do(f func(context.Context, *core.Schedule, string, string, core.TargetHints, core.CollectOptions) ([]core.Run, error)) *MockRunCollectorCollectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunCollectorCollectCall) DoAndReturn(f func(context.Context, *core.Schedule, string, string, core.TargetHints, core.CollectOptions) ([]core.Run, error)) *MockRunCollectorCollectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Service mocks base method.
func (m *MockRunCollector) Service() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Service")
	s, _ := ret[0].(string)
	return s
}

// Service indicates an expected call of Service.
func (mr *MockRunCollectorMockRecorder) Service() *MockRunCollectorServiceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Service", reflect.TypeOf((*MockRunCollector)(nil).Service))
	return &MockRunCollectorServiceCall{Call: call}
}

// MockRunCollectorServiceCall wrap *gomock.Call
type MockRunCollectorServiceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunCollectorServiceCall) Return(s string) *MockRunCollectorServiceCall {
	c.Call = c.Call.Return(s)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunCollectorServiceCall) Do(f func() string) *MockRunCollectorServiceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunCollectorServiceCall) DoAndReturn(f func() string) *MockRunCollectorServiceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
