// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock

package mocks

import (
	"context"
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/account"
	"go.uber.org/mock/gomock"
)

// MockAccountInformationAPI is a mock of AccountInformationAPI interface.
type MockAccountInformationAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAccountInformationAPIMockRecorder
	isgomock struct{}
}

// MockAccountInformationAPIMockRecorder is the mock recorder for MockAccountInformationAPI.
type MockAccountInformationAPIMockRecorder struct {
	mock *MockAccountInformationAPI
}

// NewMockAccountInformationAPI creates a new mock instance.
func NewMockAccountInformationAPI(ctrl *gomock.Controller) *MockAccountInformationAPI {
	mock := &MockAccountInformationAPI{ctrl: ctrl}
	mock.recorder = &MockAccountInformationAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountInformationAPI) EXPECT() *MockAccountInformationAPIMockRecorder {
	return m.recorder
}

// GetAccountInformation mocks base method.
func (m *MockAccountInformationAPI) GetAccountInformation(context1 context.Context, getAccountInformationInput *account.GetAccountInformationInput, fns ...func(*account.Options)) (*account.GetAccountInformationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{context1, getAccountInformationInput}
	for _, a := range fns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountInformation", varargs...)
	getAccountInformationOutput, _ := ret[0].(*account.GetAccountInformationOutput)
	err, _ := ret[1].(error)
	return getAccountInformationOutput, err
}

// GetAccountInformation indicates an expected call of GetAccountInformation.
func (mr *MockAccountInformationAPIMockRecorder) GetAccountInformation(context1, getAccountInformationInput any,
	fns ...any) *MockAccountInformationAPIGetAccountInformationCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{context1, getAccountInformationInput}, fns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountInformation", reflect.TypeOf((*MockAccountInformationAPI)(nil).GetAccountInformation), varargs...)
	return &MockAccountInformationAPIGetAccountInformationCall{Call: call}
}

// MockAccountInformationAPIGetAccountInformationCall wrap *gomock.Call
type MockAccountInformationAPIGetAccountInformationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAccountInformationAPIGetAccountInformationCall) Return(getAccountInformationOutput *account.GetAccountInformationOutput, err error) *MockAccountInformationAPIGetAccountInformationCall {
	c.Call = c.Call.Return(getAccountInformationOutput, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAccountInformationAPIGetAccountInformationCall) Do(f func(context.Context, *account.GetAccountInformationInput, ...func(*account.Options)) (*account.GetAccountInformationOutput, error)) *MockAccountInformationAPIGetAccountInformationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAccountInformationAPIGetAccountInformationCall) DoAndReturn(f func(context.Context, *account.GetAccountInformationInput, ...func(*account.Options)) (*account.GetAccountInformationOutput, error)) *MockAccountInformationAPIGetAccountInformationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
